#!/usr/bin/env bash
# ── MakaOS libogg port ────────────────────────────────────────────────
# libogg is the Ogg bitstream container (2 TUs).  Xonotic/DarkPlaces links
# it statically (the PRELOAD build) for Ogg Vorbis audio.  Manual source-list
# cross-compile like the freetype/xkbcommon ports -- no autotools configure.
set -euo pipefail
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BUILD_DIR="$REPO_ROOT/build"
SRC="$BUILD_DIR/third_party/libogg-1.3.5"
SYSROOT="${SYSROOT:-$BUILD_DIR/sysroot}"
CROSS_CC="$REPO_ROOT/toolchain/bin/x86_64-pc-makaos-gcc"
CROSS_AR="$REPO_ROOT/toolchain/bin/x86_64-pc-makaos-ar"
log() { printf '[port-libogg] %s\n' "$*" >&2; }
[ -d "$SRC" ] || { log "FATAL: $SRC not found (fetch libogg-1.3.5 first)"; exit 1; }

# config_types.h is normally generated by configure; provide the 64-bit-host
# resolution (standard fixed-width ints).
mkdir -p "$SYSROOT/usr/include/ogg"
cat > "$SYSROOT/usr/include/ogg/config_types.h" <<'EOF'
#ifndef __CONFIG_TYPES_H__
#define __CONFIG_TYPES_H__
#include <stdint.h>
typedef int16_t  ogg_int16_t;
typedef uint16_t ogg_uint16_t;
typedef int32_t  ogg_int32_t;
typedef uint32_t ogg_uint32_t;
typedef int64_t  ogg_int64_t;
typedef uint64_t ogg_uint64_t;
#endif
EOF
cp "$SRC/include/ogg/ogg.h"      "$SYSROOT/usr/include/ogg/"
cp "$SRC/include/ogg/os_types.h" "$SYSROOT/usr/include/ogg/"

OBJDIR="$BUILD_DIR/ogg_objs"; mkdir -p "$OBJDIR"
CFLAGS=(-O2 -fPIC -I "$SYSROOT/usr/include" -I "$SRC/include")
objs=()
for s in bitwise framing; do
    o="$OBJDIR/$s.o"; objs+=("$o")
    "$CROSS_CC" "${CFLAGS[@]}" -c "$SRC/src/$s.c" -o "$o"
done
rm -f "$SYSROOT/usr/lib/libogg.a"
"$CROSS_AR" rcs "$SYSROOT/usr/lib/libogg.a" "${objs[@]}"

cat > "$SYSROOT/usr/lib/pkgconfig/ogg.pc" <<EOF
prefix=/usr
libdir=\${prefix}/lib
includedir=\${prefix}/include
Name: ogg
Description: Ogg bitstream library
Version: 1.3.5
Libs: -L\${libdir} -logg
Cflags: -I\${includedir}
EOF
log "done -- $(stat -c%s "$SYSROOT/usr/lib/libogg.a") bytes -> libogg.a"
